### ISSUE TITLE
Async Support

### ISSUE THREAD

**Issue by krugertech** [asherber/StaTypPocoQueries.PetaPoco#1]
Nice work. Any plan on adding async support ?
i..e return db.Query**Async**<Category>(c => c.ParentID == parentCategoryId).ToList();

**Comment by asherber** [comment]
Sure, that's a good idea. I think when I put this out it was shortly before PetaPoco included async operations.

**Comment by asherber** [comment]
I'm sorry for the delay. Async operations have been added to v1.3.2, available from NuGet.
