### ISSUE TITLE
Query does not seem to support ColumnAttribute

### ISSUE THREAD

**Issue by nj-db** [asherber/StaTypPocoQueries.PetaPoco#2]
Hi, 
I like what you have done with these extensions.
I have tried to use your Query extensions with a POCO class that has a property using the PetaPoco ColumnAttribute but it returns a SQL exception that a column with the property name does not exist in the table.

**Comment by asherber** [comment]
This is a limitation of the underlying [StaTypPocoQuerues](https://github.com/d-p-y/statically-typed-poco-queries) library.  I opened [a ticket](https://github.com/d-p-y/statically-typed-poco-queries/issues/6) there to see if this functionality can be added.

**Comment by asherber** [comment]
This functionality has been added in the base library. Give me a day or two to add the needed code here.

**Comment by asherber** [comment]
Sorry for the delay. This has been added to v1.3.2, available from NuGet.
