### ISSUE TITLE
In queries are not supported

### ISSUE THREAD

**Issue by Qq247534686** [asherber/StaTypPocoQueries.PetaPoco#3]
Hello I run this code 
`db.Fetch<Sys_ModuleButtonEntity>(p => p.F_FullName.Contains("2"));`
VS2017 report error:
conditions has unexpected type p.F_FullName.Contains("2")
System exception in FSharp.Core.dll

**Comment by asherber** [comment]
This is a limitation of the underlying StaTypPocoQueries library. To see what features are supported by the library, scroll down to the bottom of https://github.com/d-p-y/statically-typed-poco-queries

**Comment by Qq247534686** [comment]
Thank you very much
