### ISSUE TITLE
Are ValueConverterAttributes supported?

### ISSUE THREAD

**Issue by nils-a** [asherber/StaTypPocoQueries.PetaPoco#5]
I have a setup where I use a simple `ValueConverterAttribute` to save enums as `String` in the database.
Using *StaTypPocoQueries.PetaPoco* for querying of those pocos results in errors like:

> SqlException: Conversion failed when converting the nvarchar value 'SomeValue' to data type int

I'm using `database.SingleOrDefaultAsync(x => x.SomeString == "SomeString" && x.SomeEnum == MyEnumType.SomeValue)`

Now, in "pure" PetaPoco I did not have the problem, but I also had `database.SingleOrDefaultAsync(Sql.Builder.Where("[SomeString] = @0 AND [SomeEnum] = @1", "SomeString", Enum.GetName(typeof(MyEnumType), MyEnumType.SomeValue))` - which is to say I did the conversion of the `Converter` manually in code.

So I guess the question really is: Am I doing something wrong, or this this not a supported case to do?

**Comment by asherber** [comment]
I see what you're trying to do, and I agree that it would be useful. But it's not currently supported.

This library is just a set of bindings between the underlying [StaTypPocoQueries](https://github.com/d-p-y/statically-typed-poco-queries) library, which handles the translation between the `Expression<Func<T, bool>>`  and a SQL query with parameters. If you want the translator to be smart enough to apply value converters, you'll need to open a ticket in the other library.  Right now, all it's doing is turning `x.SomeEnum` into a column name and `MyEnumType.SomeValue` into a parameter; it's not caring about types.

**Comment by nils-a** [comment]
I have opened https://github.com/d-p-y/statically-typed-poco-queries/issues/8 to track my request.

**Comment by d-p-y** [comment]
Hi, I've implemented support for this feature in StaTypPocoQueries.Core. See [issue #8](https://github.com/d-p-y/statically-typed-poco-queries/issues/8) for more info.

**Comment by asherber** [comment]
@d-p-y Thank you! I'll take a look and add the corresponding hooks in this library.

**Comment by asherber** [comment]
This is now supported by v1.4.1. Thanks to @d-p-y for the support.

**Comment by nils-a** [comment]
Thanks @asherber and @d-p-y for getting this done so quickly. 🙇 
I will try to implement it next week!
